plugins {
    id 'com.android.application'
}

android {
    namespace 'com.hyperps3.emulator'
    compileSdk 35

    defaultConfig {
        applicationId "com.hyperps3.emulator"
        minSdk 29
        targetSdk 35
		versionCode 62
		versionName "0.6.2"
        ndkVersion "27.0.12077973"

        ndk {
            abiFilters 'arm64-v8a'
        }

        externalNativeBuild {
            cmake {
              cppFlags "-std=c++17 -fPIC"
              arguments "-DANDROID_STL=c++_static",
				  "-DCMAKE_JOB_POOLS=compile_pool=2;link_pool=1",
			  "-DCMAKE_JOB_POOL_COMPILE=compile_pool",
			  "-DCMAKE_JOB_POOL_LINK=link_pool",
                          "-DCMAKE_CXX_FLAGS=-O3 -DNDEBUG -ffast-math",
                          "-DCMAKE_C_FLAGS=-O3 -DNDEBUG -ffast-math",
                          "-DCMAKE_BUILD_TYPE=Release"
            }
        }
    }

    buildTypes {
        release {
            minifyEnabled false
            proguardFiles getDefaultProguardFile('proguard-android-optimize.txt'), 'proguard-rules.pro'
        }
    }
    compileOptions {
        sourceCompatibility JavaVersion.VERSION_1_8
        targetCompatibility JavaVersion.VERSION_1_8
    }

    externalNativeBuild {
        cmake {
            path file("src/main/cpp/CMakeLists.txt")
            version "3.31.6"
        }
    }

    packagingOptions {
        jniLibs {
            useLegacyPackaging = true
        }
    }
}

dependencies {
    implementation 'androidx.appcompat:appcompat:1.7.0'
    implementation 'com.google.android.material:material:1.12.0'
    implementation 'androidx.constraintlayout:constraintlayout:2.1.4'
    implementation 'androidx.preference:preference:1.2.1'
}
